server.port=8080

spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

# PostgreSQL RDS
spring.datasource.url=jdbc:postgresql://database-uady.ckudetdcrnsb.us-east-1.rds.amazonaws.com:5432/postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=Chepo2004
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# AWS Credentials
aws.region=us-east-1
aws.access-key-id=ASIAY5MUHN7B7AISYJHB
aws.secret-access-key=7H+7oljStoI2WpJZRvAGk7TBj8mcZY0mmnFLm0ik
aws.session-token=7H+7oljStoI2WpJZRvAGk7TBj8mcZY0mmnFLm0ik
aws_session_token=IQoJb3JpZ2luX2VjEEgaCXVzLXdlc3QtMiJHMEUCIFkS2VwZ5YD3T57VHkaMofMt632/Vf8U0UVcd1XhdwdWAiEAuJRoz0B0Me057tqcwtI3Vk8+quCNZxpTzsfRSXYIRQcqsAIIERAAGgw2MTI4ODA1NzY0NTEiDNy4s2s8ZjI9jVoUqSqNAml3X/6H1iB/lS/BNl9+NxBm4+wIFon5QijCUzVIal8EoAl5gjFCdYvt/Mt5PE4gW7ok0AKgIdxISigN85LN6R5mmRlsjzvxxDx1ugc7sWCmylrCr8KtGYjbJ/ftxv6thKYaBwEXhAUubXyQ85TsirspU20Xe2xFlGNzL13YpVm5w57i5lrgKzwlelen1oIODQUOI7TTE+G1FBTzWr0cDV2Jekc6FEdjOjO5qqp/licjYBAlbxj1lX7VaIlog2+OjSdY6E23aCHOYuvDcT7EcGmWU8TFdovU+knqPprxB7YlYIt53kepZUFaw+pTb8uEdG+ja4KKk+lIVsTHawsdR/ItIsxVMmiVe+ddb+XGMJ3BvtAGOp0BnkeA86QTEQ/r6s6HSIe8O9zHaFI/SsmdWHuXiRviksn5GfFDId3gaNqFRKJE1WuRwkkTCXsZmmc4vQqN36L+NT7Q53TpfqnXjIWtOcKKHuAQO03U7bA/4M1oWbfv9886PQvehIwQepvQa0bJ8wGaEOfK9IqlcgDL0iRsBaQulI/Q69UWDNumNT1HJY/aPzlUwtj9aWRr1znEL6De+w
# AWS SNS
aws.sns.topic-arn=arn:aws:sns:us-east-1:612880576451:Avisos-UADY

# AWS S3
aws.s3.bucket=uady-alumnos-612880576451-us-east-1-an
